apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''MYSQL_DATABASE'']}'
    template.openshift.io/expose-password: '{.data[''MYSQL_PASSWORD'']}'
    template.openshift.io/expose-root_password: '{.data[''MYSQL_ROOT_PASSWORD'']}'
    template.openshift.io/expose-username: '{.data[''MYSQL_USER'']}'
  labels:
    template: mysql-persistent-template
  name: {{ .Values.database_service_name }}
stringData:
  MYSQL_DATABASE: {{ .Values.MYSQL_DATABASE }}
  MYSQL_PASSWORD: {{ .Values.MYSQL_PASSWORD }}
  MYSQL_ROOT_PASSWORD: {{ .Values.MYSQL_ROOT_PASSWORD }}
  MYSQL_USER: {{ .Values.MYSQL_USER }}
