apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''MYSQL_DATABASE'']}'
    template.openshift.io/expose-password: '{.data[''MYSQL_ROOT_PASSWORD'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  labels:
    template: mysql-persistent-template
  name: {{ .Values.database_service_name }}
stringData:
  MYSQL_DATABASE: {{ .Values.mysql_database }}
  MYSQL_PASSWORD: {{ .Values.mysql_password }}
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql_root_password }}
  MYSQL_USER: {{ .Values.mysql_user }}
