annotations:
apiVersion: v2
appVersion: 0.0.5
description: 'This content is experimental, do not use it in production. MySQL database
  service, with persistent storage. For more information about using this template,
  including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/8.0/root/usr/share/container-scripts/mysql/README.md.  NOTE:
  Scaling to more than one replica is not supported. You must have persistent volumes
  available in your cluster to use this template.'
kubeVersion: '>=1.20.0'
name: redhat-mysql-persistent
sources:
- https://github.com/lebonvivant-sys/helm
tags: database,mysql
version: 0.0.5
