annotations:
  charts.openshift.io/digest: sha256:6caf533969e00939d28e894c72bcd2d5e61c18da35e824d87ac6ef7f5b9e5c6f
  charts.openshift.io/lastCertifiedTimestamp: "2025-08-12T13:28:05.354477+00:00"
  charts.openshift.io/name: Red Hat MySQL database service, with persistent storage
    (experimental)
  charts.openshift.io/provider: Red Hat
  charts.openshift.io/providerType: community
  charts.openshift.io/supportedOpenShiftVersions: '>=4.7'
  charts.openshift.io/testedOpenShiftVersion: N/A
apiVersion: v2
appVersion: 0.1.4
description: 'This content is experimental, do not use it in production. MySQL database
  service, with persistent storage. For more information about using this template,
  including OpenShift considerations, see https://github.com/sclorg/mysql-container/blob/master/8.0/root/usr/share/container-scripts/mysql/README.md.  NOTE:
  Scaling to more than one replica is not supported. You must have persistent volumes
  available in your cluster to use this template.'
kubeVersion: '>=1.20.0'
name: redhat-mysql-persistent
sources:
- https://github.com/lebonvivant-sys/helm
tags: database,mysql
version: 0.1.4
