database_service_name: mysql-57-rhel7
memory_limit: 512Mi
MYSQL_DATABASE: testdb
MYSQL_PASSWORD: testp # TODO: must define a default value for .mysql_password'
MYSQL_ROOT_PASSWORD: testur # TODO: must define a default value for .mysql_root_password'
MYSQL_USER: testu # TODO: must define a default value for .mysql_user'
mysql_version: latest
namespace: openshift
volume_capacity: 1Gi
